name: Build and Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # every day
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install deps
        run: bun i

      - name: Build
        run: bun run build

      - name: Prettier
        run: bun run lint

      - name: Commit changes
        run: |-
          git diff
          git config --global user.name "lobehubbot"
          git config --global user.email "i@lobehub.com"
          git add .
          git commit -m "🤖 chore: Auto sync plugins" || exit 0
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
